<?php

namespace TaskBoxx\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BoardColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardColumnRepository extends EntityRepository
{
    public function getColumnsInOrder()
    {
        return $this->_em
             ->createQuery('SELECT c FROM TaskBoxx\FrontendBundle\Entity\BoardColumn c 
                            LEFT JOIN c.backlogItems i
                            ORDER BY c.sort_order ASC')
             ->getResult();
    }
}